baseURL: http://localhost:4040/docs
disablePathToLower: true
languageCode: en-us
title: CircleCI Documentation

ignoreFiles:
  - "[^\_].adoc" # ignore all ascidoc that starts with "_"
  - ".pdf"
  - project-walkthrough.md # TODO: Tees - this file has syntax issues that will be fixed if this migration ever ships)

defaultContentLanguage: en
languages:
  en:
    contentDir: content/english/
    languageName: English
    weight: 1;
  ja:
    contentDir: content/japanese/
    languageName: Japanese
    weight: 2;

markup:
  highlight:
    codeFences: false

  asciidocExt:
    safe: unsafe
    attributes:
      imagesdir: /docs/assets/img/docs/
      relfileprefix: ../
      outfilesuffix: /index.html
      serverversion: 3.2.0
      terraformversion: 0.15.4
      kubectlversion: 1.19
      helmversion: 3.4.0
      kotsversion: 1.47.3


  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false


# Set default "cascade" front matter
# this is useful for setting entire folders to be of a specific language
cascade:
- _target:
    path: /2.0/**
  lang: en # all pages under /2.0/** will have front matter where lang = en.


## Static Assets --
## Static assets are aggregated from two places:
### - Theme - (css, js, images specific to the styling of the site)
### - Root folder  - (screenshots used for content).
staticDir:
- static
- themes/docs-theme/static


#
# All custom site variables go under "params"
# TODO: TEES - make a prod version of this file with the correct keys
params:
  gh_url: "https://github.com/circleci/circleci-docs"

  segment: 'mAJ9W2SwLHgmJtFkpaXWCbwEeNk9D8CZ'
  optimizely: "GfYszBpMkefBSwiiEkH3b3"

  rollbar_env: development


  algolia:
    application_id: U0RXNGRK45
    api_key: dd49f5b81d238d474b49645a4daed322 # search-only API Key; safe for front-end code
    index_name: documentation
    index_name_orbs: orbs-prod
    index_name_cimgs: images_prod
    extensions_to_index:
      - html
      - md
      - adoc
    nodes_to_index: 'p,h1'
    settings:
      highlightPreTag: '<strong>'
      highlightPostTag: '</strong>'
      attributesToSnippet: [
        'content:80',
        'headings',
        'title'
      ]
      attributesToHighlight: [
        'content:80',
        'headings',
        'title'
      ]
      minProximity: 3
